objects/Account.object
<CustomObject>
    <fields>
        <fullName>Calle_comercial_Inv__c</fullName>
        <label>Calle comercial Inv</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_comercial__c</fullName>
        <label>Calle comercial</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_particular_Inv__c</fullName>
        <label>Calle particular Inv</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Celular_Comercial_Inv__c</fullName>
        <label>Celular comercial Inv</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_comercial_Inv__c</fullName>
        <label>Ciudad o Provincia comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular_Inv__c</fullName>
        <label>Ciudad o Provincia particular Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular__c</fullName>
        <label>Ciudad o Provincia particular</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_FAX_Other__c</fullName>
        <description>Commercial FAX Other, used in customer creation form for &quot;Personas Naturales&quot; and &quot;Personas Jurídicas&quot;</description>
        <label>Commercial FAX Other</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Comuna_comercial_Inv__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna comercial Inv</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna comercial Inv)</relationshipLabel>
        <relationshipName>Cuentas2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_comercial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna comercial</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular_Inv__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular Inv</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna particular Inv)</relationshipLabel>
        <relationshipName>Cuentas3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna particular)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crear_Cliente__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Al marcarlo, ejecutivo solicita la creación del cliente al área de creación de Clientes</description>
        <label>Crear Cliente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ejecutivo_de_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ejecutivo de Cuenta</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Comercial_Inv__c</fullName>
        <label>Email Comercial Inv</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_Rep_Legal_Inv__c</fullName>
        <label>Email Rep Legal Inv</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Fecha_Solicitud_Crear_Cliente__c</fullName>
        <label>Fecha Solicitud Crear Cliente</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Info_adicional_Inv_Oficina__c</fullName>
        <label>Info adicional Inv (Oficina,...)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_calle_comercial_Inv__c</fullName>
        <label>Número calle comercial Inv</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_comercial__c</fullName>
        <label>Número calle comercial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Number__c</fullName>
        <description>Office Number, used in customer creation form for Personas Naturales and Personas Jurídicas</description>
        <label>Office Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Otro_telefono_Comercial_Inv__c</fullName>
        <label>Otro teléfono comercial Inv</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Pais_comercial_Inv__c</fullName>
        <label>País comercial Inv</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chile</fullName>
                    <default>true</default>
                    <label>Chile</label>
                </value>
                <value>
                    <fullName>Afganistán</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Alemania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua y Barbuda</fullName>
                </value>
                <value>
                    <fullName>Arabia Saudita</fullName>
                </value>
                <value>
                    <fullName>Argelia</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaiyán</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladés</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Baréin</fullName>
                </value>
                <value>
                    <fullName>Bélgica</fullName>
                </value>
                <value>
                    <fullName>Belice</fullName>
                </value>
                <value>
                    <fullName>Benín</fullName>
                </value>
                <value>
                    <fullName>Bielorrusia</fullName>
                </value>
                <value>
                    <fullName>Birmania</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botsuana</fullName>
                </value>
                <value>
                    <fullName>Brasil</fullName>
                </value>
                <value>
                    <fullName>Brunéi</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pais_comercial__c</fullName>
        <label>País comercial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <description>RUT para Empresas y Personas (RUT for Accounts and Person Accounts)</description>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raz_n_Social__c</fullName>
        <label>Razón Social</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region_comercial_Inv__c</fullName>
        <label>Región comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telefono_fijo_comercial_Inv__c</fullName>
        <description>Utilizado por Inversiones equivale a Phone estandar que utiliza el Banco</description>
        <label>Teléfono fijo comercial Inv</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>rut_inv__c</fullName>
        <description>Requerido para Creación Cliente PJ Inversiones. Rut Rep Legal.</description>
        <inlineHelpText>Requerido para Creación Cliente Persona Jurídica de Inversiones</inlineHelpText>
        <label>Rut RL</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Comuna__c.object
<CustomObject>
    <description>Tabla de Comunas de Chile. Incluye Provincia, Región y códigos correspondientes.</description>
    <label>Comuna</label>
    <nameField>
        <label>Comuna</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>Monoproducto</fullName>
        <active>true</active>
        <businessProcess>Retail Banking</businessProcess>
        <description>Venta Monoproducto</description>
        <label>Monoproducto</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Perfil_Bolsa__c</fullName>
        <description>Campo de parámetro requerido para la integración con sistema BOLSA</description>
        <label>Perfil Bolsa</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Username_Bolsa__c</fullName>
        <description>Campo con parámetro requerido para integración con sistema BOLSA</description>
        <label>Username Bolsa</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BICE_ConsultaBolsa_Controller_Test.cls
@isTest(seeAllData= true) 
public class BICE_ConsultaBolsa_Controller_Test{

    public static testMethod void testMyController() {
        String ProfileId = [SELECT Id FROM Profile WHERE Name = 'Banca Personas Ejecutivo Cuenta'].Id;
        BICE_ConsultaBolsa_Controller bcc = new BICE_ConsultaBolsa_Controller();
       // User u = [SELECT Id FROM User WHERE ProfileId =:ProfileId AND IsActive = true AND ManagerId <> NULL LIMIT 1];
        User u = [SELECT Id, Name FROM User WHERE Name = 'SAMUEL BRAVO' LIMIT 1];
        
        System.runAs(u) {
          Comuna__c com = [SELECT Id FROM Comuna__c WHERE Name = 'SANTIAGO'];
            RecordType rtPersona = [SELECT Id FROM RecordType WHERE Name = 'Cuentas personales'];
            RecordType rtEmpresa = [SELECT Id FROM RecordType WHERE Name = 'Cuenta Empresa'];
            RecordType rtOpp = [SELECT Id FROM RecordType WHERE Name = 'Monoproducto'];
            
            Account acc = new Account();
            //////Cuenta Persona///////////
            acc.FirstName = 'INT';
            acc.LastName = '20';
            acc.RUT__c = '1234567-4';
            acc.RecordTypeId = rtPersona.Id;
            acc.Ciudad_o_Provincia_particular__c = 'SANTI';
            acc.Comuna_particular__c = com.Id;
            acc.Comuna_comercial__c = com.Id;
            acc.Comuna_comercial_Inv__c = com.Id;
            acc.Numero_comercial__c = '23213';
            //acc.Commercial_FAX_Other__c = '213213';
            acc.Office_Number__c = '111';
            acc.PersonMobilePhone = '+569898987';
            acc.Particular_Phone_Other__pc = '+568998989';
            acc.Particular_Landline__pc = '+568987878';
            acc.Spouse_RUT__pc = '16049291-0'; //Conyuge
            acc.rut_inv__c = '16049291-0'; //representante legal
            acc.Comuna_particular_Inv__c = com.Id;
            acc.Ciudad_o_Provincia_particular_Inv__c = 'asdasd';
            acc.Calle_particular_Inv__c = 'calle';
            acc.Telefono_fijo_particular_Inv__pc = '23323';
            acc.Celular_Particular_Inv__pc = '2222';
            acc.Otro_telefono_particular_Inv__pc = '111';
            acc.Calle_comercial_Inv__c = 'calle com';
            acc.Ciudad_o_Provincia_comercial_Inv__c = 'ciudad com';
            acc.Pais_comercial_Inv__c = 'Chile';
            acc.Numero_calle_comercial_Inv__c = '111';
            acc.Region_comercial_Inv__c = 'rm';
            acc.Info_adicional_Inv_Oficina__c = 'info';
            acc.Telefono_fijo_comercial_Inv__c = '12121';
            acc.Celular_comercial_Inv__c = '11111';
            acc.Otro_telefono_comercial_Inv__c = '1111';
            acc.Email_personal_Inv__pc = 'a@g.cl';
            acc.Email_comercial_Inv__c = 'a@g.cl';
            acc.Email_Rep_Legal_Inv__c = 'a@g.cl';
            acc.Raz_n_Social__c = 'razon';
            
            insert acc;
            
            Account acc2 = new Account();
            //////Cuenta Persona///////////
            acc2.Name = 'Empresa';
            acc2.RUT__c = '22385241-6';
            acc2.RecordTypeId = rtEmpresa.Id;
            
            acc2.Comuna_comercial__c = com.Id;
            acc2.Pais_comercial__c = 'Chile';
            acc2.Calle_comercial__c = 'Calle';
            acc2.Numero_comercial__c = '1111';
            acc2.Office_Number__c = '111';          
            acc2.Numero_comercial__c = '23213';
            //acc.Commercial_FAX_Other__c = '213213';
            acc2.Office_Number__c = '111';           
            acc2.Fecha_Solicitud_Crear_Cliente__c = Date.today();  
            acc2.Crear_Cliente__c = true;
            acc2.Ejecutivo_de_Cuenta__c = u.id;
            insert acc2;
            
            Opportunity op = new Opportunity();
            op.RecordTypeId = rtOpp.Id;
            op.CloseDate = Date.today();
            op.StageName = 'Contacto';
            op.Amount = 100.00;
            op.Type = 'Monoproducto';
            op.Name = 'Esta es una opp nueva';
            op.AccountId = acc.Id;
            
            insert op;
           
         ApexPages.StandardController sc = new ApexPages.StandardController(acc);
          BICE_ConsultaBolsa_Controller  testAccPlan = new BICE_ConsultaBolsa_Controller(sc);
        
          PageReference pageRef = Page.BICE_ConsultaBolsa_Btn_acc; // Add your VF page Name here
          pageRef.getParameters().put('id', String.valueOf(acc.Id));
          Test.setCurrentPage(pageRef);
            
          bcc.ConsultaBolsaCallout();
          
         
        }
    }
    public static testMethod void testLoginBolsa() {
        //String ProfileId = [SELECT Id FROM Profile WHERE Name = 'Banca Personas Ejecutivo Cuenta'].Id;
        BICE_ConsultaBolsa_Controller bcc = new BICE_ConsultaBolsa_Controller();
        User u = [SELECT Id FROM User WHERE IsActive = true AND Username_Bolsa__c <> NULL AND Perfil_Bolsa__c <> NULL LIMIT 1];
        //User u = [SELECT Id, Name FROM User WHERE FirstName = 'MARYCARMEN' LIMIT 1];
        
        System.runAs(u) {
          Comuna__c com = [SELECT Id FROM Comuna__c WHERE Name = 'SANTIAGO'];
            RecordType rtPersona = [SELECT Id FROM RecordType WHERE Name = 'Cuentas personales'];
            RecordType rtEmpresa = [SELECT Id FROM RecordType WHERE Name = 'Cuenta Empresa'];
            RecordType rtOpp = [SELECT Id FROM RecordType WHERE Name = 'Monoproducto'];
            
            Account acc = new Account();
            //////Cuenta Persona///////////
            acc.FirstName = 'INT';
            acc.LastName = '20';
            acc.RUT__c = '1234567-4';
            acc.RecordTypeId = rtPersona.Id;
            acc.Ciudad_o_Provincia_particular__c = 'SANTI';
            acc.Comuna_particular__c = com.Id;
            acc.Comuna_comercial__c = com.Id;
            acc.Comuna_comercial_Inv__c = com.Id;
            acc.Numero_comercial__c = '23213';
            //acc.Commercial_FAX_Other__c = '213213';
            acc.Office_Number__c = '111';
            acc.PersonMobilePhone = '+569898987';
            acc.Particular_Phone_Other__pc = '+568998989';
            acc.Particular_Landline__pc = '+568987878';
            acc.Spouse_RUT__pc = '16049291-0'; //Conyuge
            acc.rut_inv__c = '16049291-0'; //representante legal
            acc.Comuna_particular_Inv__c = com.Id;
            acc.Ciudad_o_Provincia_particular_Inv__c = 'asdasd';
            acc.Calle_particular_Inv__c = 'calle';
            acc.Telefono_fijo_particular_Inv__pc = '23323';
            acc.Celular_Particular_Inv__pc = '2222';
            acc.Otro_telefono_particular_Inv__pc = '111';
            acc.Calle_comercial_Inv__c = 'calle com';
            acc.Ciudad_o_Provincia_comercial_Inv__c = 'ciudad com';
            acc.Pais_comercial_Inv__c = 'Chile';
            acc.Numero_calle_comercial_Inv__c = '111';
            acc.Region_comercial_Inv__c = 'rm';
            acc.Info_adicional_Inv_Oficina__c = 'info';
            acc.Telefono_fijo_comercial_Inv__c = '12121';
            acc.Celular_comercial_Inv__c = '11111';
            acc.Otro_telefono_comercial_Inv__c = '1111';
            acc.Email_personal_Inv__pc = 'a@g.cl';
            acc.Email_comercial_Inv__c = 'a@g.cl';
            acc.Email_Rep_Legal_Inv__c = 'a@g.cl';
            acc.Raz_n_Social__c = 'razon';
            
            insert acc;
            
            Account acc2 = new Account();
            //////Cuenta Persona///////////
            acc2.Name = 'Empresa';
            acc2.RUT__c = '22385241-6';
            acc2.RecordTypeId = rtEmpresa.Id;
            
            acc2.Comuna_comercial__c = com.Id;
            acc2.Pais_comercial__c = 'Chile';
            acc2.Calle_comercial__c = 'Calle';
            acc2.Numero_comercial__c = '1111';
            acc2.Office_Number__c = '111';          
            acc2.Numero_comercial__c = '23213';
            //acc.Commercial_FAX_Other__c = '213213';
            acc2.Office_Number__c = '111';           
            acc2.Fecha_Solicitud_Crear_Cliente__c = Date.today();  
            acc2.Crear_Cliente__c = true;
            acc2.Ejecutivo_de_Cuenta__c = u.id;
            insert acc2;
            
            Opportunity op = new Opportunity();
            op.RecordTypeId = rtOpp.Id;
            op.CloseDate = Date.today();
            op.StageName = 'Contacto';
            op.Amount = 100.00;
            op.Type = 'Monoproducto';
            op.Name = 'Esta es una opp nueva';
            op.AccountId = acc.Id;
            
            insert op;
           
         ApexPages.StandardController sc = new ApexPages.StandardController(op);
          BICE_ConsultaBolsa_Controller  testAccPlan = new BICE_ConsultaBolsa_Controller(sc);
        
          PageReference pageRef = Page.BICE_ConsultaBolsa_Btn_opp; // Add your VF page Name here
       
          Test.setCurrentPage(pageRef);
            
          bcc.loginBolsa();
          //bcc.loginBolsa();
         
        }
    }
    
    public static testMethod void testBolsa(){
        Test.setMock(WebServiceMock.class, new BICE_ConsultaBolsaWS_Test());
        BICE_ConsultaBolsaWS parentObject = new BICE_ConsultaBolsaWS();
        new BICE_ConsultaBolsaWS.wscreatoken();
        new BICE_ConsultaBolsaWS.wsCreaTokenAgente();
        new BICE_ConsultaBolsaWS.wsCreaTokenAgenteResponse();
        new BICE_ConsultaBolsaWS.wscreatokenResponse();
        new BICE_ConsultaBolsaWS.wscreatokenResult();
    }
    @isTest 
    public static void coverCodeForwsValidaToken(){
        Test.setMock(WebServiceMock.class, new BICE_ConsultaBolsaWS_Test());
        BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort testObject = new BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort();
        testObject.wsValidaToken(null);
    }
    @isTest 
    public static void coverCodeForwsCreaTokenAgente(){
        Test.setMock(WebServiceMock.class, new BICE_ConsultaBolsaWS_Test());
        BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort testObject = new BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort();
        testObject.wsCreaTokenAgente(null,null,null,null,null);
    }
    @isTest 
    public static void coverCodeForwsCreaToken(){
        Test.setMock(WebServiceMock.class, new BICE_ConsultaBolsaWS_Test());
        BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort testObject = new BICE_ConsultaBolsaWS.WscreatokenejbWebPortBindingQSPort();
        testObject.wscreatoken(null,null);
    }
}