objects/Account.object
<CustomObject>
    <fields>
        <fullName>Calle_comercial_Inv__c</fullName>
        <label>Calle comercial Inv</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_particular_Inv__c</fullName>
        <label>Calle particular Inv</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_comercial_Inv__c</fullName>
        <label>Ciudad o Provincia comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular_Inv__c</fullName>
        <label>Ciudad o Provincia particular Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular__c</fullName>
        <label>Ciudad o Provincia particular</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_FAX_Other__c</fullName>
        <description>Commercial FAX Other, used in customer creation form for &quot;Personas Naturales&quot; and &quot;Personas Jurídicas&quot;</description>
        <label>Commercial FAX Other</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Comuna_comercial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna comercial</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular_Inv__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular Inv</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna particular Inv)</relationshipLabel>
        <relationshipName>Cuentas3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna particular)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Info_adicional_Inv_Oficina__c</fullName>
        <label>Info adicional Inv (Oficina,...)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_calle_comercial_Inv__c</fullName>
        <label>Número calle comercial Inv</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_comercial__c</fullName>
        <label>Número calle comercial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Number__c</fullName>
        <description>Office Number, used in customer creation form for Personas Naturales and Personas Jurídicas</description>
        <label>Office Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais_comercial_Inv__c</fullName>
        <label>País comercial Inv</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chile</fullName>
                    <default>true</default>
                    <label>Chile</label>
                </value>
                <value>
                    <fullName>Afganistán</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Alemania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua y Barbuda</fullName>
                </value>
                <value>
                    <fullName>Arabia Saudita</fullName>
                </value>
                <value>
                    <fullName>Argelia</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaiyán</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladés</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Baréin</fullName>
                </value>
                <value>
                    <fullName>Bélgica</fullName>
                </value>
                <value>
                    <fullName>Belice</fullName>
                </value>
                <value>
                    <fullName>Benín</fullName>
                </value>
                <value>
                    <fullName>Bielorrusia</fullName>
                </value>
                <value>
                    <fullName>Birmania</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botsuana</fullName>
                </value>
                <value>
                    <fullName>Brasil</fullName>
                </value>
                <value>
                    <fullName>Brunéi</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <description>RUT para Empresas y Personas (RUT for Accounts and Person Accounts)</description>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_comercial_Inv__c</fullName>
        <label>Región comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rut_inv__c</fullName>
        <description>Requerido para Creación Cliente PJ Inversiones. Rut Rep Legal.</description>
        <inlineHelpText>Requerido para Creación Cliente Persona Jurídica de Inversiones</inlineHelpText>
        <label>Rut RL</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BICE_Solicitud_Cliente__c.object
<CustomObject>
    <description>Ficha Solicitud de Clientes Utilizada por Banca Inersiones.</description>
    <fields>
        <fullName>Calle_comercial_Inv__c</fullName>
        <label>Calle comercial Inv</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_particular_Inv__c</fullName>
        <label>Calle particular Inv</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_comercial_Inv__c</fullName>
        <label>Ciudad o Provincia comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular_Inv__c</fullName>
        <label>Ciudad o Provincia particular Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular__c</fullName>
        <label>Ciudad o Provincia particular</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_FAX_Other__c</fullName>
        <description>Commercial FAX Other, used in customer creation form for &quot;Personas Naturales&quot; and &quot;Personas Jurídicas&quot;</description>
        <label>Commercial FAX Other</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Comuna_comercial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna comercial</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipName>CuentasCC1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular_Inv__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular Inv</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipName>CuentasCP2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipName>CuentasCP1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Info_adicional_Inv_Oficina__c</fullName>
        <label>Info adicional Inv (Oficina,...)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_calle_comercial_Inv__c</fullName>
        <label>Número calle comercial Inv</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_comercial__c</fullName>
        <label>Número calle comercial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Number__c</fullName>
        <description>Office Number, used in customer creation form for Personas Naturales and Personas Jurídicas</description>
        <label>Office Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais_comercial_Inv__c</fullName>
        <label>País comercial Inv</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chile</fullName>
                    <default>true</default>
                    <label>Chile</label>
                </value>
                <value>
                    <fullName>Afganistán</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Alemania</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua y Barbuda</fullName>
                </value>
                <value>
                    <fullName>Arabia Saudita</fullName>
                </value>
                <value>
                    <fullName>Argelia</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaiyán</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladés</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Baréin</fullName>
                </value>
                <value>
                    <fullName>Bélgica</fullName>
                </value>
                <value>
                    <fullName>Belice</fullName>
                </value>
                <value>
                    <fullName>Benín</fullName>
                </value>
                <value>
                    <fullName>Bielorrusia</fullName>
                </value>
                <value>
                    <fullName>Birmania</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botsuana</fullName>
                </value>
                <value>
                    <fullName>Brasil</fullName>
                </value>
                <value>
                    <fullName>Brunéi</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <description>RUT para Empresas y Personas (RUT for Accounts and Person Accounts)</description>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region_comercial_Inv__c</fullName>
        <label>Región comercial Inv</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rut_inv__c</fullName>
        <description>Requerido para Creación Cliente PJ Inversiones. Rut Rep Legal.</description>
        <label>Rut RL</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Solicitud Cliente en Sebra</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Solicitud de Cliente</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitudes Creación Cliente Sebra</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BICE_Account_SebraInt_Controller_Test.cls
@isTest(seeAllData= true) 
private class BICE_Account_SebraInt_Controller_Test{
    static testMethod void IntegracionSebra() {
       BICE_Account_SebraInt_Controller bs = new BICE_Account_SebraInt_Controller();
       BICE_Account_SebraInt_Controller.ClienteSebra cs = new BICE_Account_SebraInt_Controller.ClienteSebra();
        
        Comuna__c com1 = [SELECT Id FROM Comuna__c WHERE Name = 'CONCEPCION'];
        Comuna__c com = [SELECT Id FROM Comuna__c WHERE Name = 'SANTIAGO'];
        RecordType rtPersona = [SELECT Id FROM RecordType WHERE Name = 'Cuentas personales'];
        RecordType rtEmpresa = [SELECT Id FROM RecordType WHERE Name = 'Cuenta Empresa'];  
        
        Account acc = new Account();
        //////Cuenta Persona///////////
        acc.FirstName = 'INT';
        acc.LastName = '20';
        acc.RUT__c = '16049291-0';
        acc.RecordTypeId = rtPersona.Id;
        acc.Ciudad_o_Provincia_particular__c = 'SANTI';
        acc.Comuna_particular__c = com.Id;
        acc.Comuna_comercial__c = com.Id;
        acc.Numero_comercial__c = '23213';
        //acc.Commercial_FAX_Other__c = '213213';
        acc.Office_Number__c = '111';
        acc.PersonMobilePhone = '+569898987';
        acc.Particular_Phone_Other__pc = '+568998989';
        acc.Particular_Landline__pc = '+568987878';
        acc.Spouse_RUT__pc = '16049291-0'; //Conyuge
        acc.rut_inv__c = '16049291-0'; //representante legal
        acc.Comuna_particular_Inv__c = com.Id;
        acc.Ciudad_o_Provincia_particular_Inv__c = 'asdasd';
        acc.Calle_particular_Inv__c = 'calle';
        acc.Telefono_fijo_particular_Inv__pc = '23323';
        acc.Celular_Particular_Inv__pc = '2222';
        acc.Otro_telefono_particular_Inv__pc = '111';
        acc.Calle_comercial_Inv__c = 'calle com';
        acc.Ciudad_o_Provincia_comercial_Inv__c = 'ciudad com';
        acc.Pais_comercial_Inv__c = 'Chile';
        acc.Numero_calle_comercial_Inv__c = '111';
        acc.Region_comercial_Inv__c = 'rm';
        acc.Info_adicional_Inv_Oficina__c = 'info';
        acc.Telefono_fijo_comercial_Inv__c = '12121';
        acc.Celular_comercial_Inv__c = '11111';
        acc.Otro_telefono_comercial_Inv__c = '1111';
        acc.Email_personal_Inv__pc = 'a@g.cl';
        acc.Email_comercial_Inv__c = 'a@g.cl';
        acc.Email_Rep_Legal_Inv__c = 'a@g.cl';
        acc.Raz_n_Social__c = 'razon';
        
        insert acc;  
        acc.Raz_n_Social__c = null;
        update acc;
        
        Cuenta_Bancaria_Inv__c cb = new Cuenta_Bancaria_Inv__c();
        cb.Cliente__c = acc.id;
        cb.Banco__c = 'r&h';
        
        insert cb;
        
        BICE_Solicitud_Cliente__c bsc = new BICE_Solicitud_Cliente__c();
        bsc.Sebra_Ok__c = true;
        bsc.Cliente__c = acc.id;
        insert bsc;
        
       bs.ClienteSF(acc,bsc);
       bs.xmlRequest();
       bs.ActualizarFechaSebra();
       bs.Redireccionar();
       bs.SEBRACallout();
        ApexPages.StandardController sc = new ApexPages.standardController(acc);
        BICE_Account_SebraInt_Controller ext = new BICE_Account_SebraInt_Controller(sc);
        BICE_Account_SebraInt_Controller.ClienteSebra xa = new BICE_Account_SebraInt_Controller.ClienteSebra();
        BICE_Account_SebraInt_Controller.direccion xb = new BICE_Account_SebraInt_Controller.direccion();
        BICE_Account_SebraInt_Controller.email xc = new BICE_Account_SebraInt_Controller.email();
        BICE_Account_SebraInt_Controller.telefono xd = new BICE_Account_SebraInt_Controller.telefono();
        BICE_Account_SebraInt_Controller.CuentaBancaria xe = new BICE_Account_SebraInt_Controller.CuentaBancaria();
        BICE_Account_SebraInt_Controller.personaRelacionada xf = new BICE_Account_SebraInt_Controller.personaRelacionada();
       //BICE_Account_SebraInt_Controller.ActualizaSolicitudCliente(bsc);
    }
}