objects/Account.object
<CustomObject>
    <fields>
        <fullName>Apartment__c</fullName>
        <label>Apartment</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_comercial__c</fullName>
        <label>Calle comercial</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle_particular__c</fullName>
        <label>Calle particular</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad_o_Provincia_particular__c</fullName>
        <label>Ciudad o Provincia particular</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commercial_Cellphone__c</fullName>
        <label>Teléfono móvil comercial</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Commercial_FAX_Other__c</fullName>
        <description>Commercial FAX Other, used in customer creation form for &quot;Personas Naturales&quot; and &quot;Personas Jurídicas&quot;</description>
        <label>Commercial FAX Other</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Commercial_Landline__c</fullName>
        <description>Commercial Landline, used in customer creation form for &quot;Personas Naturales&quot; and &quot;Personas Jurídicas&quot;</description>
        <label>Commercial Landline</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Comuna_comercial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna comercial</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comuna_particular__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comuna particular</label>
        <referenceTo>Comuna__c</referenceTo>
        <relationshipLabel>Cuentas (Comuna particular)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crear_Cliente__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Al marcarlo, ejecutivo solicita la creación del cliente al área de creación de Clientes</description>
        <label>Crear Cliente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ejecutivo_de_Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ejecutivo de Cuenta</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fecha_Solicitud_Crear_Cliente__c</fullName>
        <label>Fecha Solicitud Crear Cliente</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_de_declaracion_de_margen__c</fullName>
        <label>Fecha de declaración de margen</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Integracion_sebra__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sirve para identificar cuando un cliente se este creando en Sebra y no genere llamando a integracion 10.</description>
        <label>Integracion sebra</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Numero_comercial__c</fullName>
        <label>Número calle comercial</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_particular__c</fullName>
        <label>Número calle particular</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Number__c</fullName>
        <description>Office Number, used in customer creation form for Personas Naturales and Personas Jurídicas</description>
        <label>Office Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais_comercial__c</fullName>
        <label>País comercial</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pais_particular__c</fullName>
        <label>País particular</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Pais</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <description>RUT para Empresas y Personas (RUT for Accounts and Person Accounts)</description>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taxes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pago de IVA´s</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Comuna__c.object
<CustomObject>
    <description>Tabla de Comunas de Chile. Incluye Provincia, Región y códigos correspondientes.</description>
    <label>Comuna</label>
    <nameField>
        <label>Comuna</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Apellido_materno__c</fullName>
        <label>Apellido materno</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cargo__c</fullName>
        <description>lista de valores con cargos posibles para el contacto</description>
        <inlineHelpText>seleccione un cargo para el contacto</inlineHelpText>
        <label>Cargo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apoderado</fullName>
                </value>
                <value>
                    <fullName>Sin definir</fullName>
                </value>
                <value>
                    <fullName>Decorador</fullName>
                </value>
                <value>
                    <fullName>Gerente General</fullName>
                </value>
                <value>
                    <fullName>Arquitecto</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Abogado</fullName>
                </value>
                <value>
                    <fullName>Periodista</fullName>
                </value>
                <value>
                    <fullName>Gerente de Relacione</fullName>
                </value>
                <value>
                    <fullName>Jefe de Relaciones P</fullName>
                </value>
                <value>
                    <fullName>Especialista de Rela</fullName>
                </value>
                <value>
                    <fullName>Representante de Ven</fullName>
                </value>
                <value>
                    <fullName>Fiscal</fullName>
                </value>
                <value>
                    <fullName>Abogado Jefe</fullName>
                </value>
                <value>
                    <fullName>Abogado Subjefe</fullName>
                </value>
                <value>
                    <fullName>Abogado Senior</fullName>
                </value>
                <value>
                    <fullName>Abogado Junior</fullName>
                </value>
                <value>
                    <fullName>Procurador</fullName>
                </value>
                <value>
                    <fullName>Gerente Contralorma</fullName>
                </value>
                <value>
                    <fullName>Asesor Tributario</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_Contacto__c</fullName>
        <description>Tipo de contacto</description>
        <inlineHelpText>Seleccione el tipo de contacto</inlineHelpText>
        <label>Tipo de Contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ejecutivo Máximo</fullName>
                </value>
                <value>
                    <fullName>Ejecutivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BICE_AccountTriggerHandler_Test.cls
@isTest(seeAllData= true) 
private class BICE_AccountTriggerHandler_Test{
    static testMethod void All() {
        BICE_AccountTriggerHandler ba = new BICE_AccountTriggerHandler(true,200);
        Comuna__c com1 = [SELECT Id FROM Comuna__c WHERE Name = 'CONCEPCION'];
        Comuna__c com = [SELECT Id FROM Comuna__c WHERE Name = 'SANTIAGO'];
        RecordType rtPersona = [SELECT Id FROM RecordType WHERE Name = 'Cuentas personales en CIF'];
        RecordType rtEmpresa = [SELECT Id FROM RecordType WHERE Name = 'Cuenta Empresa en CIF'];
        List<Account> ListaAcc = new List<Account>();  
        Set<Id> SetIds = new Set<Id>();
         Map<Id, Account> m = new Map<Id, Account>();
         Map<Id, Account> oldm = new Map<Id, Account>();
         User u = [SELECT id FROM User WHERE FirstName = 'MA EUGENIA' LIMIT 1];
         User u2 = [SELECT id FROM User WHERE FirstName = 'MARYCARMEN' LIMIT 1];
        
        
            Account acc = new Account();
            //////Cuenta Persona///////////
            acc.FirstName = 'INT';
            acc.LastName = '20';
            acc.RUT__c = '16049291-0';
            acc.RecordTypeId = rtPersona.Id;
            acc.Ciudad_o_Provincia_particular__c = 'SANTI';
            acc.Comuna_particular__c = com.Id;
            acc.Pais_particular__c = 'Chile';
            acc.Calle_particular__c = 'CallePart';
            acc.Numero_particular__c = '111';
            acc.Apartment__c = '1111';
            acc.Comuna_comercial__c = com.Id;
            acc.Pais_comercial__c = 'Chile';
            acc.Calle_comercial__c = 'Calle';
            acc.Numero_comercial__c = '1111';
            acc.Office_Number__c = '111';          
            acc.Numero_comercial__c = '23213';
            //acc.Commercial_FAX_Other__c = '213213';
            acc.Office_Number__c = '111';
            acc.PersonMobilePhone = '+569898987';
            acc.Particular_Phone_Other__pc = '+568998989';
            acc.Particular_Landline__pc = '+568987878';
            acc.Phone = '+5689898980';
            acc.Fecha_Solicitud_Crear_Cliente__c = Date.today(); 
            acc.Crear_Cliente__c = true;
            acc.Ejecutivo_de_Cuenta__c = u.id;
            
            insert acc;
            BICE_Account_Int10 a10 = new BICE_Account_Int10();
            //BICE_Account_Int10.callInt10(acc.id, 'xml');
            BICE_Account_Int10.updateAccount(acc.Id, '1234');
            m.put(acc.id, acc);
            
            acc.Fecha_de_declaracion_de_margen__c = Date.today();
            acc.Phone = '+5681111111';
            update acc;
            
            ListaAcc.add(acc);
            SetIds.add(acc.id);        
            oldm.put(acc.id,acc);
            
            ba.setComunas(ListaAcc);
            ba.OnBeforeInsert(ListaAcc);
            ba.OnAfterInsert(ListaAcc);
            BICE_AccountTriggerHandler.OnAfterInsertAsync(SetIds);
            ba.validateIfCallInt10(ListaAcc);
            ba.OnBeforeUpdate(ListaAcc,ListaAcc,oldm,m);
            BICE_AccountTriggerHandler.FormatoFecha(acc.Fecha_Solicitud_Crear_Cliente__c, '20/05/1777');
    
        
            acc = new Account();
            //////Cuenta Persona///////////
            acc.Name = 'Empresa x';
            acc.RUT__c = '22385241-6';
            acc.RecordTypeId = rtEmpresa.Id;
            
            acc.Comuna_comercial__c = com.Id;
            acc.Pais_comercial__c = 'Chile';
            acc.Calle_comercial__c = 'Calle 1';
            acc.Numero_comercial__c = '11115';
            acc.Office_Number__c = '1114';          
            acc.Numero_comercial__c = '232133';
            //acc.Commercial_FAX_Other__c = '213213';
            acc.Office_Number__c = '1112';           
            acc.Fecha_Solicitud_Crear_Cliente__c = Date.today();  
            acc.Crear_Cliente__c = true;
            acc.Ejecutivo_de_Cuenta__c = u.id;
            
            insert acc;
            
            m.put(acc.id, acc);
        
        	acc.Calle_comercial__c = 'lejos';
        	update acc;
            
      
            
            ListaAcc.add(acc);
            SetIds.add(acc.id);        
            oldm.put(acc.id,acc);
            
            
            ba.setComunas(ListaAcc);
            ba.OnBeforeInsert(ListaAcc);
            ba.OnAfterInsert(ListaAcc);
            BICE_AccountTriggerHandler.OnAfterInsertAsync(SetIds);
            ba.validateIfCallInt10(ListaAcc);
            ba.OnBeforeUpdate(ListaAcc,ListaAcc,oldm,m);
            BICE_AccountTriggerHandler.FormatoFecha(acc.Fecha_Solicitud_Crear_Cliente__c, '20/05/1777');
        
        
        
            acc = new Account();
            //////Cuenta Persona///////////
            acc.Name = 'Empresa 2';
            acc.RUT__c = '89120-7';
            acc.RecordTypeId = rtEmpresa.Id;           
            //acc.Comuna_comercial__c = com.Id;
            acc.Pais_comercial__c = 'Chile';
            acc.Calle_comercial__c = 'Calle';
            acc.Numero_comercial__c = '1111';
            acc.Office_Number__c = '111';          
            acc.Numero_comercial__c = '23213456';
            //acc.Commercial_FAX_Other__c = '213213';
            acc.Office_Number__c = '111';
            acc.Commercial_Cellphone__c = '+568989898';   
            acc.Phone = '+568989898';   
            acc.Commercial_Landline__c = '+562656565'; 
            acc.Commercial_FAX_Other__c = '+568989859';    
            acc.Fecha_Solicitud_Crear_Cliente__c = Date.today();  
            acc.Crear_Cliente__c = true;
            acc.Ejecutivo_de_Cuenta__c = u.id;
            acc.Taxes__c = true;
        	acc.Integracion_Sebra__c = true;
            
            insert acc;
        
        	acc.Office_Number__c = '12312';
        	update acc;
            
            Contact c = new Contact();
            c.Cargo__c = 'Apoderado';
            c.Tipo_de_Contacto__c = 'Ejecutivo Máximo';
            c.Email = 'conta@cont.cl';
            c.Apellido_materno__c = 'Materno';
            c.FirstName = 'Nombre';
            c.LastName = 'Apellido';
            c.MobilePhone = '+568989898';
            c.Fax = '+5688977';
            c.Phone = '+562589859';
            c.AccountId = acc.id;
            
            insert c;
        
            m.put(acc.id, acc);
            
      
            
            ListaAcc.add(acc);
            SetIds.add(acc.id);        
            oldm.put(acc.id,acc);
            
            BICE_AccountTriggerHandler.getAccountContacts(c.Id);
            ba.setComunas(ListaAcc);
            ba.OnBeforeInsert(ListaAcc);
            ba.OnAfterInsert(ListaAcc);
            BICE_AccountTriggerHandler.OnAfterInsertAsync(SetIds);
            ba.validateIfCallInt10(ListaAcc);
            ba.OnBeforeUpdate(ListaAcc,ListaAcc,oldm,m);
            BICE_AccountTriggerHandler.FormatoFecha(acc.Fecha_Solicitud_Crear_Cliente__c, '20/05/1777');
            Boolean x = ba.IsTriggerContext;
            x = ba.IsVisualforcePageContext;
            x = ba.IsWebServiceContext;
            x = ba.IsExecuteAnonymousContext;
        
    }

}